# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Backward Sampler for the Bounded Coalescent
#'
#' Samples the number of lineages at specified times given forward
#' probabilities
#'
#' @param forward_probs 2D array of probabilities from the forward algorithm.
#' @param times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param ne Effective population size.
#' @param bound Bound time.
#' @param bound_size Number of lineages at the bound (default 1).
#' @export
backward_sampler_c <- function(forward_probs, times, leaves, ne, bound, bound_size = 1L) {
    .Call(`_BoundedCoalescent_backward_sampler_c`, forward_probs, times, leaves, ne, bound, bound_size)
}

#' Determine blocks of coalescent events from backward sample
#'
#' @param sample Sample of number of lineages from backward sampler
#' @param times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param bound Bound time.
#' @export
block_coalescences_c <- function(sample, times, leaves, bound) {
    .Call(`_BoundedCoalescent_block_coalescences_c`, sample, times, leaves, bound)
}

#' Separate coalescences in a block
#'
#' @param coalescences Number of coalescences in block.
#' @param time_lower Lower bound time of the block.
#' @param time_upper Upper bound time of the block.
#' @param lineages_upper Number of lineages at the start of the block.
#' @param ne Effective population size.
#' @export
separate_coalescences_c <- function(coalescences, time_lower, time_upper, lineages_upper, ne) {
    .Call(`_BoundedCoalescent_separate_coalescences_c`, coalescences, time_lower, time_upper, lineages_upper, ne)
}

#' Constrain coalescence events to unique time intervals
#'
#' @param sample Sample of number of lineages from backward sampler
#' @param times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param ne Effective population size.
#' @param bound Bound time.
#' @export
constrain_coalescences_c <- function(sample, times, leaves, ne, bound) {
    .Call(`_BoundedCoalescent_constrain_coalescences_c`, sample, times, leaves, ne, bound)
}

#' Sample a coalescence time within a specified interval
#'
#' @param time_lower Lower bound time of the interval.
#' @param time_upper Upper bound time of the interval.
#' @param lineages Starting number of lineages.
#' @param ne Effective population size.
#' @export
sample_coalescence_time_c <- function(time_lower, time_upper, lineages, ne) {
    .Call(`_BoundedCoalescent_sample_coalescence_time_c`, time_lower, time_upper, lineages, ne)
}

#' Forward Algorithm for the Bounded Coalescent
#'
#' Calculate the forward probabilities for the bounded coalescent.
#'
#' @param times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param ne Effective population size.
#' @param bound Bound time.
#' @export
forward_algorithm_c <- function(times, leaves, ne, bound) {
    .Call(`_BoundedCoalescent_forward_algorithm_c`, times, leaves, ne, bound)
}

#' Sample coalescence times for the bounded coalescenct
#'
#' @param times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param ne Effective population size.
#' @param bound Bound time.
#' @param nsam Number of samples (deafault 1).
sample_bounded_times_c <- function(times, leaves, ne, bound, nsam = 1L) {
    .Call(`_BoundedCoalescent_sample_bounded_times_c`, times, leaves, ne, bound, nsam)
}

#' Calculate coalescent probabilities (homochronous)
#'
#' Calculate the probability of i lineages coalescing down to j <= i lineages
#' in time dt in the homochronous setting.
#'
#' @param i Integer value for the starting number of lineages.
#' @param j Integer value for the final number of lineages.
#' @param dt Time period over which coalescences can occur.
#' @param ne Effective population size.
#' @export
homochronous_probability <- function(i, j, dt, ne) {
    .Call(`_BoundedCoalescent_homochronous_probability`, i, j, dt, ne)
}

#' Calculate the likelihood under the bounded coalescence
#'
#' @param leaf_times Times that leaves are added.
#' @param leaves Number of leaves at each time point.
#' @param coalescence_times Times of coalescences.
#' @param ne Effective population size.
#' @param bound Bound time.
bounded_times_likelihood_c <- function(leaf_times, leaves, coalescence_times, ne, bound) {
    .Call(`_BoundedCoalescent_bounded_times_likelihood_c`, leaf_times, leaves, coalescence_times, ne, bound)
}

#' Rejection sampling coalescence times for the bounded coalescenct
#'
#' @param times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param ne Effective population size.
#' @param bound Bound time.
#' @param nsam Number of samples (deafault 1).
rejection_bounded_times <- function(times, leaves, ne, bound, nsam = 1L) {
    .Call(`_BoundedCoalescent_rejection_bounded_times`, times, leaves, ne, bound, nsam)
}

