# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate coalescent probabilities (homochronous)
#'
#' Calculate the probability of i lineages coalescing down to j <= i lineages
#' in time dt in the homochronous setting.
#'
#' @param i Integer value for the starting number of lineages.
#' @param j Integer value for the final number of lineages.
#' @param dt Time period over which coalescences can occur.
#' @param Ne Effective population size.
#' @export
homochronous_probability <- function(i, j, dt, Ne) {
    .Call(`_BoundedCoalescent_homochronous_probability`, i, j, dt, Ne)
}

