# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Constrain coalescence events to unique time intervals
#'
#' @param sample Sample of number of lineages from backward sampler
#' @param times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param ne Effective population size.
#' @param bound Bound time.
constrain_coalescences_c <- function(sample, times, leaves, ne, bound, const_lower, const_upper, const_lineages, const_events) {
    .Call(`_BoundedCoalescent_constrain_coalescences_c`, sample, times, leaves, ne, bound, const_lower, const_upper, const_lineages, const_events)
}

#' Calculate coalescent probabilities (homochronous)
#'
#' Calculate the probability of i lineages coalescing down to j <= i lineages
#' in time dt in the homochronous setting.
#'
#' @param i Integer value for the starting number of lineages.
#' @param j Integer value for the final number of lineages.
#' @param dt Time period over which coalescences can occur.
#' @param ne Effective population size.
homochronous_probability <- function(i, j, dt, ne) {
    .Call(`_BoundedCoalescent_homochronous_probability`, i, j, dt, ne)
}

#' Forward Algorithm for the Bounded Coalescent
#'
#' Calculate the forward probabilities for the bounded coalescent.
#'
#' @param times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param ne Effective population size.
#' @param bound Bound time.
#' @param forward_probs Array to store probabilities.
forward_algorithm_c <- function(times, leaves, ne, bound, forward_probs) {
    invisible(.Call(`_BoundedCoalescent_forward_algorithm_c`, times, leaves, ne, bound, forward_probs))
}

#' Backward Sampler for the Bounded Coalescent
#'
#' Samples the number of lineages at specified times given forward
#' probabilities
#'
#' @param forward_probs 2D array of probabilities from the forward algorithm.
#' @param times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param ne Effective population size.
#' @param bound Bound time.
#' @param bound_size Number of lineages at the bound (default 1).
backward_sampler_c <- function(forward_probs, times, leaves, ne, bound, lineages, bound_size = 1L) {
    .Call(`_BoundedCoalescent_backward_sampler_c`, forward_probs, times, leaves, ne, bound, lineages, bound_size)
}

#' Sample coalescence times for the bounded coalescenct
#'
#' @param times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param ne Effective population size.
#' @param bound Bound time.
#' @param nsam Number of samples (deafault 1).
sample_bounded_times_c <- function(times, leaves, ne, bound, nsam = 1L) {
    .Call(`_BoundedCoalescent_sample_bounded_times_c`, times, leaves, ne, bound, nsam)
}

#' Rejection sampling coalescence times for the bounded coalescenct
#'
#' @param times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param ne Effective population size.
#' @param bound Bound time.
#' @param nsam Number of samples (deafault 1).
rejection_bounded_times_c <- function(times, leaves, ne, bound, nsam = 1L) {
    .Call(`_BoundedCoalescent_rejection_bounded_times_c`, times, leaves, ne, bound, nsam)
}

#' Sample topology given coalescent times.
#'
#' @param leaf_times Vector of ordered sampling times for leaves.
#' @param leaves Number of leaves taken at each sampling time.
#' @param coalescence_times Vector of ordered coalescence times.
sample_topology_c <- function(leaf_times, leaves, coalescence_times) {
    .Call(`_BoundedCoalescent_sample_topology_c`, leaf_times, leaves, coalescence_times)
}

#' Calculate the likelihood under the bounded coalescence
#'
#' @param leaf_times Times that leaves are added.
#' @param leaves Number of leaves at each time point.
#' @param coalescence_times Times of coalescences.
#' @param ne Effective population size.
#' @param bound Bound time.
bounded_times_likelihood_c <- function(leaf_times, leaves, coalescence_times, ne, bound) {
    .Call(`_BoundedCoalescent_bounded_times_likelihood_c`, leaf_times, leaves, coalescence_times, ne, bound)
}

